### ISSUE TITLE
It does not open the ".odt", ".ods" files ...

### ISSUE THREAD

**Issue by emanuc** [flathub/org.onlyoffice.desktopeditors#14]
I have Ubuntu 20.04 LTS
Flatpak version: 1.6.3
OnlyOffice version: 5.5.1

When I open the ".ods", "odt" files (files created with LibreOffice) by the file manager (nautilus), it does not open the file directly, but opens onlyoffice on the home, strangely I have a ".xlsx" file and opens it directly.
If I create the file with onlyoffice and save it, then I can open it directly.

I have tried onlyoffice desktop from the ".deb" and it works regularly, so it's a problem with the flatpak version on flathub.
But I prefer to use the flatpak version to have the app always updated.
Thanks.

**Comment by janxkoci** [comment]
I cannot reproduce this on my system, which is elementary OS 5 (based on Ubuntu 18.04). I have flatpak 1.8.3 (elementary backported newer version, as flatpak is a default feature on the OS) and OnlyOffice 6.2.

Consider closing.

**Comment by janxkoci** [comment]
Also note that OnlyOffice internally converts ODF (odt, ods, odp) formats to OOXML (docx, xlsx, pptx) to allow editing, as the project is build around OOXML format and focuses mostly on that. The ODF support is more of a bonus.

**Comment by KelvinNovais** [comment]
Hello @janxkoci! I had the same problem mentioned by @emanuc.

**If you are on Gnome/Nautilus:**

**1. Navigate to the file  you want to change the default association;
2. Right click > Properties;
3. Open With;
4. Select the new application > Set as default.**

I think the problem is more related to GNOME and the system first default application for that file extension. However, I think you could include this information on the documentation to avoid people waste time (as I did) thinking the problem is the OnlyOffice or the Flatpak.

- OS: PopOS 22.04 LTS
- OnlyOffice version: 7.1.1.57
- Flatpak version: 1.12.7

Thank you.

**Comment by emanuc** [comment]
The problem for me was solved, tried with version 7.1.1 installed by flathub

**Comment by ShockwaveNN** [comment]
@KelvinNovais If you provide an exact scenario of how to reproduce this problem - I can file an issue to our developers and they figure out if this is a GNOME issue or our issue

Because for me everything works fine

1. I'm using popos 22.04 and installed ONLYOFFICE DesktopEditors via flatpak
2. I've tried to open odt file - by double click - and it was not associated to ONLYOFFICE DesktopEditors and opened in other editors
3. Then I've changed association - it's opened fine

I do not understand how this situation that odt files is not accosted with ONLYOFFICE DesktopEditors, but opening in it and showing home page, maybe some leftovers of other installation types (from deb)

**Comment by janxkoci** [comment]
Hi @ShockwaveNN,
As I wrote above, I don't have this issue with ODF formats (like .odt, .ods, and so on) - these files open without any issue right away.

However, the description by OP sounds a lot similar to an issue I _do have_ with TSV format ([tracked here](https://github.com/ONLYOFFICE/DocumentServer/issues/1052)). Trying to open such file throws an error dialog about "unsupported format" over an unresponsive OnlyOffice window:

![Snímek z 2022-08-25 13 05 24](https://user-images.githubusercontent.com/19331850/186648687-01724c45-1e1c-4d1a-85f2-a47a01be4dbd.png)

It seems to me that OnlyOffice has some problems _opening_ these formats (even though in reality it can handle them just fine - my installation opens ODF without issue and TSV after renaming the extension to .csv, even if the separator is still `tab`). So maybe the issue is with input format filters or something like that.

**Comment by ShockwaveNN** [comment]
Yes, and issue with TSV is still not resolved, so let's not mees up several issue in one

**Comment by janxkoci** [comment]
Yeah, my comment was more about the error dialog and input filters as potential culprits.

**Comment by KelvinNovais** [comment]
@ShockwaveNN sorry, I had a misunderstanding with the topics, while searching for an existing issue...
I thought the subject was "OnlyOffice doesn't open .od* _by default_". My problem was solved just by changing the default application, such as I described. Everything is working fine.

Thank you! and again, sorry for the misunderstanding.

**Comment by ShockwaveNN** [comment]
In that case, I'll close this issue since author confirmed that the problem is solved

If you got any question and problem - I think it's better to create a new issue for that
